# Generated by Django 5.0.3 on 2024-03-25 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_author_full_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='full_name',
            new_name='fullname',
        ),
    ]
